// This file is generated by scripts/generate-workflow-imports.js
// DO NOT EDIT BY HAND

export const WORKFLOW_IMPORTS: Record<string, () => Promise<any>> = {
  '_example': () => import('./_example/index'),
  'code-review': () => import('./code-review/index'),
};

export default WORKFLOW_IMPORTS;
